---
- name: Open INPUT for UDP port 500 for the Internet Key Exchange (IKE) protocol
  iptables:
    action: insert
    chain: INPUT
    protocol: udp
    jump: ACCEPT
    source_port: 500
    destination_port: 500
  notify:
  - Save iptables rules
  - Restart iptables

- name: Open OUTPUT for UDP port 500 for the Internet Key Exchange (IKE) protocol
  iptables:
    action: insert
    chain: OUTPUT
    protocol: udp
    jump: ACCEPT
    source_port: 500
    destination_port: 500
  notify:
  - Save iptables rules
  - Restart iptables

- name: Open INPUT for UDP port 4500 for IKE NAT-Traversal
  iptables:
    action: insert
    chain: INPUT
    protocol: udp
    jump: ACCEPT
    source_port: 4500
    destination_port: 4500
  notify:
  - Save iptables rules
  - Restart iptables

- name: Open OUTPUT for UDP port 4500 for IKE NAT-Traversal
  iptables:
    action: insert
    chain: OUTPUT
    protocol: udp
    jump: ACCEPT
    source_port: 4500
    destination_port: 4500
  notify:
  - Save iptables rules
  - Restart iptables

- name: Open INPUT for Protocol 50 for Encapsulated Security Payload (ESP) IPsec packets 
  iptables:
    action: insert
    chain: INPUT
    protocol: udp
    jump: ACCEPT
    source_port: 50
    destination_port: 50
  notify:
  - Save iptables rules
  - Restart iptables

- name: Open OUTPUT for Protocol 50 for Encapsulated Security Payload (ESP) IPsec packets 
  iptables:
    action: insert
    chain: OUTPUT
    protocol: udp
    jump: ACCEPT
    source_port: 50
    destination_port: 50
  notify:
  - Save iptables rules
  - Restart iptables

- name: Open INPUT for Protocol 51 for Authentication Header (AH) traffic
  iptables:
    action: insert
    chain: INPUT
    protocol: udp
    jump: ACCEPT
    source_port: 51
    destination_port: 51
  notify:
  - Save iptables rules
  - Restart iptables

- name: Open OUTPUT for Protocol 51 for Authentication Header (AH) traffic
  iptables:
    action: insert
    chain: OUTPUT
    protocol: udp
    jump: ACCEPT
    source_port: 51
    destination_port: 51
  notify:
  - Save iptables rules
  - Restart iptables
