---
- name: Write node-to-node ipsec secrets file
  template:
    src: ipsec-node-to-node-tunnels.secrets.j2
    dest: /etc/ipsec.d/overcloud-{{ network }}-node-to-node-tunnels.secrets
    mode: '0600'
  notify:
  - Restart ipsec

- name: Write ipsec.secrets file
  template:
    src: ipsec-vip-tunnels.secrets.j2
    dest: /etc/ipsec.d/overcloud-{{ network }}-vip-tunnels.secrets
    mode: '0600'
  notify:
  - Restart ipsec

- name: Write node-to-node ipsec tunnel configuration
  template:
    src: ipsec-node-to-node-tunnels.conf.j2
    dest: /etc/ipsec.d/overcloud-{{ network }}-node-to-node-tunnels.conf
    mode: '0640'
  notify:
  - Restart ipsec

- name: Write VIP ipsec tunnel configuration
  template:
    src: ipsec-vip-tunnels.conf.j2
    dest: /etc/ipsec.d/overcloud-{{ network }}-vip-tunnels.conf
    mode: '0640'
  notify:
  - Restart ipsec

