---
- include: setup.yml

- name: Get the current node's internal API IP address
  shell: grep "{{ ansible_hostname }}.internalapi$" /etc/hosts | awk '{print $1}'
  register: current_internalapi_ip_register

# This outputs the hosts as lines consisting of <fqdn>,<IP>
- name: Get the controller internal API hostnames and IP addresses
  shell: grep "{{ overcloud_controller_identifier }}.*internalapi$" /etc/hosts | awk '{print $3","$1}'
  register: internalapi_controllers_register

- name: Get the current node's storage IP address
  shell: grep "{{ ansible_hostname }}.storage$" /etc/hosts | awk '{print $1}'
  register: current_storage_ip_register

# This outputs the hosts as lines consisting of <fqdn>,<IP>
- name: Get the controller storage hostnames and IP addresses
  shell: grep "{{ overcloud_controller_identifier }}.*storage$" /etc/hosts | awk '{print $3","$1}'
  register: storage_controllers_register

- name: Get the overcloud internal API VIP address
  shell: hiera -c /etc/puppet/hiera.yaml internal_api_virtual_ip
  register: internalapi_vip_register

- name: Get the overcloud redis VIP address
  shell: hiera -c /etc/puppet/hiera.yaml redis_vip
  register: redis_vip_register

- name: Get the overcloud storage VIP address
  shell: hiera -c /etc/puppet/hiera.yaml storage_virtual_ip
  register: storage_vip_register

- name: Set the networks IPs facts
  set_fact:
    networks:
      - name: internalapi
        current_ip: "{{current_internalapi_ip_register.stdout}}"
        controllers: "{{internalapi_controllers_register.stdout_lines}}"
        vips:
          - name: internalapi
            ip: "{{internalapi_vip_register.stdout}}"
          - name: redis
            ip: "{{redis_vip_register.stdout}}"
      - name: storage
        current_ip: "{{current_storage_ip_register.stdout}}"
        controllers: "{{storage_controllers_register.stdout_lines}}"
        vips:
          - name: storage
            ip: "{{storage_vip_register.stdout}}"

- name: Determine if pacemaker is running
  shell: systemctl is-active pacemaker
  register: pacemaker_running
  ignore_errors: yes

# This returns the hostname (short) of the node hosting the VIP
- name: Determine which node is hosting the VIP
  shell: pcs status | grep ip- | sed 's/ip-//' | awk '{print $1"\t"$4}' | grep "{{ networks[0]['vips'][0]['ip'] }}" | awk '{print $2}'
  register: node_hosting_the_vip
  when: pacemaker_running.stdout == 'active'

- name: Add uniqueids = no to ipsec setup configuration
  lineinfile:
    dest: /etc/ipsec.conf
    regexp: '^\s+uniqueids'
    insertafter: '^config setup'
    line: "\tuniqueids=no"
  notify:
  - Restart ipsec

- include: ipsec-conf.yml
  with_items: "{{ networks }}"

- include: firewall.yml

- meta: flush_handlers

# Permissions gotten from http://www.linux-ha.org/doc/dev-guides/_installing_and_packaging_resource_agents.html
- name: Install TripleO IPSEC resource agent
  copy:
    src: ipsec-resource-agent.sh
    dest: /usr/lib/ocf/resource.d/heartbeat/tripleo-ipsec
    mode: '0755'
  register: resource_agent

# This queries the VIPs for all networks and flattens them into a list
# that contains a dict with the "name" and "ip" for each VIP entry.
- include: resource-agent.yml
  with_items: "{{ networks|json_query('[*].vips[]')|list }}"
