---
- name: Save iptables rules
  shell: iptables-save > /etc/sysconfig/iptables

- name: Restart iptables
  service:
    name: iptables
    state: restarted

- name: Restart ipsec
  service:
    name: ipsec
    state: restarted
