---
- name: Save iptables rules
  shell: iptables-save > /etc/sysconfig/iptables

- name: Restore iptables rules
  shell: iptables-restore

- name: Restart ipsec
  service:
    name: ipsec
    state: restarted
