---
- when: not ipsec_uninstall_tunnels|bool
  block:
  - include: setup.yml

  - include: legacy.yml
    when: enabled_networks is not defined

  - include: opportunistic-ipsec.yml
    when: enabled_networks is defined

- when: ipsec_uninstall_tunnels|bool
  block:
  - name: Find tunnel configurations to delete
    find:
      paths: /etc/ipsec.d/
      patterns: overcloud-*
    register: files_to_delete

  - name: Remove tunnel configurations
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
    notify:
    - Restart ipsec
