---
- when: ipsec_uninstall_tunnels|bool or ipsec_upgrade_tunnels|bool
  block:
  - name: Find tunnel configurations to delete
    find:
      paths: /etc/ipsec.d/
      patterns: overcloud-*
    register: configs_to_delete

  - name: Remove tunnel configurations
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ configs_to_delete.files }}"
    notify:
    - Restart ipsec

  - name: Find policy configurations to delete
    find:
      paths: /etc/ipsec.d/policies/
      patterns: overcloud-*
    register: policies_to_delete

  - name: Remove tunnel configurations
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ policies_to_delete.files }}"
    notify:
    - Restart ipsec

- when: not ipsec_uninstall_tunnels|bool or ipsec_upgrade_tunnels|bool
  block:
  - include: setup.yml

  # This doesn't use the dynamic inventory
  - include: legacy.yml
    when: enabled_networks is not defined and ipsec_install_legacy|bool

  # This uses the dynamic inventory
  - include: ipsec.yml
    when: enabled_networks is defined
